# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 956ef4e90e35c41c1ba8a483f6fb40f7e916b3e3d9bede45ec1d09b4aaa28971b22deb58ed2865bac2d5166d4df4d8c167e7ab2c3199d79825791970a8f67a59

test:
  secret_key_base: c89b4bb8aaedf26149dcc431341aee8b6b3ce6c19f03ae642803e02f745f6c93f147fea9449d198cbbf1b0ce4f7f3d2daa86c5eb89549c2e872951a944abdcaa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
